WDP181002-12 Add RWD for mobiles to nav and banner bar
stepek/wdp-1810 pull request #10
Opened 2018-10-29 15:14 UTC by Piet-Tia

2018-11-03 12:46 UTC, mateuszwrobel requested changes

2018-11-03 12:46 UTC, mateuszwrobel commented on src/sass/components/_header.scss
> +        border: 1px solid green;
to chyba jest niepotrzebne ;)

2018-11-03 21:17 UTC, ralesz submitted a review, later dismissed

2018-11-04 16:23 UTC, stepek approved these changes

2018-11-05 09:39 UTC, mateuszwrobel approved these changes

2018-11-05 10:29 UTC, merged