WDP181002-11
stepek/wdp-1810 pull request #13
Opened 2018-11-02 23:20 UTC by Piet-Tia

2018-11-03 12:50 UTC, mateuszwrobel requested changes

2018-11-03 12:50 UTC, mateuszwrobel commented on src/sass/components/_header.scss
> +            display: none;
trochę za dużo tych styli ;)

2018-11-03 12:50 UTC, mateuszwrobel commented on src/sass/components/_header.scss
> +              a {
jeśli używałbyś klas, nie musiałbyś robić aż takich zagnieżdżeń

2018-11-03 15:17 UTC, mateuszwrobel submitted a review, later dismissed

2018-11-03 17:23 UTC, ralesz submitted a review, later dismissed

2018-11-04 18:53 UTC, stepek approved these changes

2018-11-04 18:59 UTC, ralesz approved these changes

2018-11-04 18:59 UTC, merged