WDP181002-21 New section PROMO
stepek/wdp-1810 pull request #17
Opened 2018-11-06 22:46 UTC by ralesz

2018-11-07 09:42 UTC, Piet-Tia commented on src/sass/components/_section--promo.scss
> +                background-color: $primary;
Może warto dodać klasę .active, tam gdzie jest &:hover, żeby zasymulować (dopóki nie ma skryptów) aktywny obecny slajd.

2018-11-07 09:46 UTC, Piet-Tia commented on src/index.html
> +                      <div class="btn-main-small no-hover">$ 30.00</div>
Tutaj chyba trzeba dodać klasę .price-button, żeby była zmiana tła nowej ceny na hover

2018-11-07 10:12 UTC, Piet-Tia requested changes
Może dodaj jeszcze @extend .hover-animation do klas, które mają zmianę koloru/tła na hover (kropki w "Hot Deals", buttony-strzałki po prawej)...

2018-11-07 11:33 UTC, Piet-Tia submitted a review, later dismissed

2018-11-07 17:04 UTC, stepek commented on src/sass/components/_section--promo.scss
> +    .sale1 {
dlaczego akurat `sale1`?

2018-11-07 17:24 UTC, ralesz commented on src/sass/components/_section--promo.scss
> +    .sale1 {
Pytasz o nazwę? Tak właściwie powinno być sale_new - bo jest to zmodyfikowana class .sale z oryginalnego _product_box. Zmienić nazwę - czy chodzi o inną zmianę?

2018-11-09 06:28 UTC, stepek approved these changes

2018-11-09 08:59 UTC, Piet-Tia approved these changes

2018-11-09 09:11 UTC, merged