WDP181002-18
stepek/wdp-1810 pull request #19
Opened 2018-11-11 00:02 UTC by Piet-Tia

2018-11-11 16:48 UTC, ralesz commented
W kodzie nic specjalnego nie wyłapałem. Co do breakpointów niech się Mentorzy wypowiedzą. 
- po najechaniu na kropkę - kursor powinien być zmieniany na łapkę.

Nie jest to powiedziane wprost w tasku, także może być, ale pewnie nie musi:
- brak podświetlania aktywnego slajdu (pomarańczowy kolor kropki) / również powinien się zmieniać po kliknięciu.

![zrzut ekranu 2018-11-11 o 17 36 53](https://user-images.githubusercontent.com/41360722/48315618-bfe5b880-e5d8-11e8-95b2-bded9835325a.png)

2018-11-11 17:13 UTC, ralesz requested changes
W kodzie nic specjalnego nie wyłapałem. Co do breakpointów niech się Mentorzy wypowiedzą.

po najechaniu na kropkę - kursor powinien być zmieniany na łapkę.
Nie jest to powiedziane wprost w tasku, także może być, ale pewnie nie musi:

brak podświetlania aktywnego slajdu (pomarańczowy kolor kropki) / również powinien się zmieniać po kliknięciu.

![zrzut ekranu 2018-11-11 o 17 36 53](https://user-images.githubusercontent.com/41360722/48315963-5f0caf00-e5dd-11e8-9db3-db7387f376a1.png)

2018-11-12 18:39 UTC, ralesz submitted a review, later dismissed

2018-11-13 06:36 UTC, stepek submitted a review, later dismissed

2018-11-15 12:56 UTC, ralesz approved these changes

2018-11-15 13:12 UTC, mateuszwrobel approved these changes

2018-11-15 13:34 UTC, merged