WDP181002-34 Create README.md
stepek/wdp-1810 pull request #21
Opened 2018-11-12 10:52 UTC by Piet-Tia

2018-11-13 06:12 UTC, stepek requested changes

2018-11-13 06:12 UTC, stepek commented on README.md
> +https://stepek.github.io/wdp-1810
Please change to https://pedantic-mahavira-4d4694.netlify.com

2018-11-14 06:42 UTC, stepek approved these changes

2018-11-14 16:46 UTC, ralesz approved these changes

2018-11-14 18:31 UTC, merged