Wdp181002-8
stepek/wdp-1810 pull request #5
Opened 2018-10-26 13:04 UTC by Piet-Tia

2018-10-26 22:29 UTC, mateuszwrobel submitted a review, later dismissed

2018-10-27 20:30 UTC, stepek requested changes

2018-10-27 20:30 UTC, stepek commented on src/index.html
> +</html>
Każdy plik powinien kończyć się pustą linią wynika.

2018-10-27 20:30 UTC, stepek commented on src/sass/components/_post-box.scss
> +      color: #000000;
please use variables for colors

2018-10-27 20:30 UTC, stepek commented on src/sass/components/_post-box.scss
> +      color: rgb(103,103,103);
please use variables for colors

2018-10-30 06:35 UTC, stepek submitted a review, later dismissed

2018-10-30 19:35 UTC, mateuszwrobel requested changes

2018-10-30 19:35 UTC, mateuszwrobel commented on src/sass/_variables.scss
> +$grey-rgb-103:rgb(103,103,103);
variable should have meaningful name that provides information what it is for, not it's content

2018-11-03 12:42 UTC, mateuszwrobel submitted a review, later dismissed

2018-11-03 19:29 UTC, stepek submitted a review, later dismissed

2018-11-03 21:12 UTC, ralesz approved these changes

2018-11-04 06:16 UTC, stepek approved these changes

2018-11-04 17:54 UTC, merged