Wdp181002-5
stepek/wdp-1810 pull request #6
Opened 2018-10-26 20:58 UTC by Piet-Tia

2018-10-26 22:36 UTC, mateuszwrobel requested changes

2018-10-26 22:36 UTC, mateuszwrobel commented on src/sass/components/_button.scss
> +    background-color: $primary;
it'd be better if icon on active was white.
state for non-active: black icon, white background
hover for non-active: white icon, orange background
state for active: white icon, orange background
hover for active: black icon, white background
main menu works this way.

2018-10-30 06:36 UTC, stepek requested changes

2018-10-30 06:36 UTC, stepek commented on src/sass/components/_button.scss
> +}
Brak pustej linii na końcu pliku w tym commcie ją usuwasz

2018-11-03 12:43 UTC, mateuszwrobel approved these changes

2018-11-03 19:29 UTC, stepek approved these changes

2018-11-03 20:20 UTC, merged