WDP181002-6 added box: old price
stepek/wdp-1810 pull request #7
Opened 2018-10-28 13:48 UTC by ralesz

Added box: old price.

2018-10-28 17:25 UTC, stepek requested changes
Plików .DS_Store nie powinno się commitować. Możesz go usunąć a w następnym komicie dodać do gitignore `.DS_Store`

2018-10-28 17:25 UTC, stepek commented on src/sass/_variables.scss
> +$old-price-bg:rgb(189, 189, 189);
Proszę podawaj kolory w tym samym formacie.

2018-10-30 06:36 UTC, stepek submitted a review, later dismissed

2018-10-30 19:36 UTC, mateuszwrobel requested changes

2018-10-30 19:36 UTC, mateuszwrobel commented on src/sass/_variables.scss
> +$old-price-bg:	#bdbdbd;
to many whitespaces

2018-10-30 19:54 UTC, mateuszwrobel approved these changes

2018-10-30 19:57 UTC, merged